### PR TITLE
Branch 2.5

### PR DESCRIPTION
**Pull request by codeboyInGitHub**
doesn't work on CentOS6.8

[root@localhost openvswitch-2.5.2]# uname -r
2.6.32-642.6.1.el6.x86_64
[root@localhost openvswitch-2.5.2]# cat /etc/issue
CentOS release 6.8 (Final)
Kernel \r on an \m
[root@localhost openvswitch-2.5.2]# 

Errors:
In file included from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/skbuff.h:17,
                 from include/linux/if_ether.h:137,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_ether.h:4,
                 from include/linux/netdevice.h:29,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/netdevice.h:4,
                 from include/linux/if_arp.h:26,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_arp.h:4,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/datapath.c:23:
include/linux/skbuff.h: In function 'skb_probe_transport_header':
include/linux/skbuff.h:1407: error: implicit declaration of function 'skb_flow_dissect'
In file included from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/skbuff.h:17,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/actions.c:21:
include/linux/skbuff.h: In function 'skb_probe_transport_header':
include/linux/skbuff.h:1407: error: implicit declaration of function 'skb_flow_dissect'
In file included from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/skbuff.h:17,
                 from include/linux/if_ether.h:137,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_ether.h:4,
                 from include/linux/netdevice.h:29,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/netdevice.h:4,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/dp_notify.c:19:
include/linux/skbuff.h: In function 'skb_probe_transport_header':
include/linux/skbuff.h:1407: error: implicit declaration of function 'skb_flow_dissect'
In file included from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/datapath.c:24:
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h: In function '__vlan_hwaccel_push_inside':
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h:68: error: implicit declaration of function 'vlan_tx_tag_get'
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h: In function 'vlan_hwaccel_push_inside':
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h:86: error: implicit declaration of function 'vlan_tx_tag_present'
In file included from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/actions.c:31:
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h: In function '__vlan_hwaccel_push_inside':
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h:68: error: implicit declaration of function 'vlan_tx_tag_get'
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h: In function 'vlan_hwaccel_push_inside':
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h:86: error: implicit declaration of function 'vlan_tx_tag_present'
In file included from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/skbuff.h:17,
                 from include/linux/if_ether.h:137,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_ether.h:4,
                 from include/linux/netdevice.h:29,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/netdevice.h:4,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/flow.c:20:
include/linux/skbuff.h: In function 'skb_probe_transport_header':
include/linux/skbuff.h:1407: error: implicit declaration of function 'skb_flow_dissect'
In file included from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/../vlan.h:22,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/../datapath.h:34,
                 from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/dp_notify.c:24:
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h: In function '__vlan_hwaccel_push_inside':
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h:68: error: implicit declaration of function 'vlan_tx_tag_get'
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h: In function 'vlan_hwaccel_push_inside':
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h:86: error: implicit declaration of function 'vlan_tx_tag_present'
make[2]: *** [/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/datapath.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/dp_notify.o] Error 1
make[2]: *** [/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/actions.o] Error 1
In file included from /root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/flow.c:23:
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h: In function '__vlan_hwaccel_push_inside':
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h:68: error: implicit declaration of function 'vlan_tx_tag_get'
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h: In function 'vlan_hwaccel_push_inside':
/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/../datapath/linux/compat/include/linux/if_vlan.h:86: error: implicit declaration of function 'vlan_tx_tag_present'
make[2]: *** [/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux/flow.o] Error 1
make[1]: *** [_module_/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux] Error 2
make[1]: Leaving directory `/usr/src/kernels/2.6.32-642.6.1.el6.x86_64'
make: *** [default] Error 2
make: Leaving directory `/root/rpmbuild/BUILD/openvswitch-2.5.2/_default/datapath/linux'
error: Bad exit status from /var/tmp/rpm-tmp.iL3jw9 (%build)

### CODE REVIEW

**Comment by blp** [comment]
Please reporrt your bug to bugs@openvswitch.org.  Also, please don't report bugs as if they were pull requests.
